// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Infraestructura.Data;

namespace Store.Infraestructura.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20210820093340_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Store.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgeRestriction")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .IsFixedLength(true);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Price")
                        .HasMaxLength(1000)
                        .HasColumnType("real")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 12,
                            Company = "TomHanksor",
                            Description = "Awesome Bicycle",
                            Name = "Bicycle Tom Hanks",
                            Price = 123f
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 99,
                            Company = "HandsOver",
                            Description = "Awesome Train",
                            Name = "Train Handsome",
                            Price = 123f
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 80,
                            Company = "BearLand",
                            Description = "Cute BearLand",
                            Name = "Teddy bear",
                            Price = 1000f
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 80,
                            Company = "DuckHunter",
                            Description = "Ducker",
                            Name = "Rubber ducky",
                            Price = 200f
                        },
                        new
                        {
                            Id = 5,
                            AgeRestriction = 80,
                            Company = "GoodGuyCompany",
                            Description = "GoodGuyCompany Description",
                            Name = "Good guy doll",
                            Price = 800f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
